INSERT INTO CITY (CITY_ID, PROVINCE, NAME) VALUES (1, 'ALACANT', 'ALICANTE');
INSERT INTO CITY (CITY_ID, PROVINCE, NAME) VALUES (2, 'ALACANT', 'TORREVIEJA');
INSERT INTO CITY (CITY_ID, PROVINCE, NAME) VALUES (3, 'ALACANT', 'BENIDORM');
INSERT INTO CITY (CITY_ID, PROVINCE, NAME) VALUES (4, 'ALACANT', 'ELCHE');
INSERT INTO CITY (CITY_ID, PROVINCE, NAME) VALUES (5, 'VALENCIA', 'VALENCIA');
INSERT INTO CITY (CITY_ID, PROVINCE, NAME) VALUES (6, 'VALENCIA', 'GANDIA');
INSERT INTO CITY (CITY_ID, PROVINCE, NAME) VALUES (7, 'MADRID', 'MADRID');
INSERT INTO CITY (CITY_ID, PROVINCE, NAME) VALUES (8, 'MADRID', 'GRIÑÓN');

INSERT INTO ADDRESS (ADDRESS_ID, STREET, NUMBER, CITY_ID) VALUES (1, 'MAESTRO BARBIERI', '4B', 1);
INSERT INTO ADDRESS (ADDRESS_ID, STREET, NUMBER, CITY_ID) VALUES (2, 'CALLE CASTAÑOS', '25', 1);
INSERT INTO ADDRESS (ADDRESS_ID, STREET, NUMBER, CITY_ID) VALUES (3, 'CARRER RUPERTO CHAPÍ', '125', 4);
INSERT INTO ADDRESS (ADDRESS_ID, STREET, NUMBER, CITY_ID) VALUES (4, 'CALLE DE SEGOVIA', '212', 7);
INSERT INTO ADDRESS (ADDRESS_ID, STREET, NUMBER, CITY_ID) VALUES (5, 'MAGIC STREET', '125', null);

INSERT INTO APPLICATION (ID, ADDRESS_ID, SUBMISSION_DATE, NAME, QUANTITY, QUANTITY2) VALUES (1, 1, TIMESTAMP '2016-05-05 00:00:00', 'GARCIA', 10, 10);
INSERT INTO APPLICATION (ID, ADDRESS_ID, SUBMISSION_DATE, NAME, QUANTITY, QUANTITY2) VALUES (2, 4, TIMESTAMP '2016-06-05 00:00:00', 'RODRIGUEZ', 14, 14);

INSERT INTO SERVICE (ID, NAME, ACTIVE_FROM, ACTIVE_TO) VALUES (1, 'SERVICEA', TIMESTAMP '2016-05-05 00:00:00', TIMESTAMP '2099-05-05 00:00:00');
INSERT INTO SERVICE (ID, NAME, ACTIVE_FROM, ACTIVE_TO) VALUES (2, 'SERVICEB', TIMESTAMP '2016-05-05 00:00:00', TIMESTAMP '2017-05-05 00:00:00');
