INSERT INTO ITEM (ID, NAME) VALUES (1, 'Laptop');
INSERT INTO ITEM (ID, NAME) VALUES (2, 'Desktop');
INSERT INTO ITEM (ID, NAME) VALUES (3, 'Monitor');
INSERT INTO ITEM (ID, NAME) VALUES (4, 'Tablet');
