INSERT INTO APPLICANT (APPLICANT_ID, NAME, SURNAME) VALUES (1, 'Jorge', 'Costa');
INSERT INTO APPLICANT (APPLICANT_ID, NAME, SURNAME) VALUES (2, 'Enrique', 'Mendoza');

INSERT INTO SERVICE (SERVICE_ID, NAME) VALUES (1, 'SERVICE_A');
INSERT INTO SERVICE (SERVICE_ID, NAME) VALUES (2, 'SERVICE_B');
